services:
  api:
    build: .
    container_name: gatcha_generator_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env.docker
    depends_on:
      - minio
      - postgres
    networks:
      - gatcha_network

  postgres:
    image: postgres:16-alpine
    container_name: gatcha_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gatcha_user
      POSTGRES_PASSWORD: gatcha_password
      POSTGRES_DB: gatcha_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gatcha_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gatcha_user -d gatcha_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: gatcha_pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gatcha.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - gatcha_network
    depends_on:
      - postgres

  minio:
    image: minio/minio
    container_name: gatcha_generator_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - gatcha_network

networks:
  gatcha_network:
    driver: bridge

volumes:
  minio_data:
  postgres_data:
  pgadmin_data:
